import os
from datetime import datetime
from langchain_core.tools import tool


@tool
def pdf_generator(input_data: str) -> str:
    """
    Generate a professional PDF report from findings and save it to the reports folder.
    Use this when you need to create a polished report that can be downloaded or shared.
    Input format: 'title|||findings|||recommendations'
    Where each section is separated by |||
    Returns the saved PDF file path.
    """
    try:
        # Lazy import reportlab (only when function is called)
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
        from reportlab.lib import colors
    except ImportError:
        return "ERROR: reportlab library not installed. Run: pip install reportlab"
    
    try:
        if "|||" not in input_data:
            return "Wrong format. Use: 'Report Title|||findings text|||recommendations text'"

        parts = input_data.split("|||", 2)
        if len(parts) < 2:
            return "Incomplete input. Provide at least title and findings."

        title = parts[0].strip()
        findings = parts[1].strip() if len(parts) > 1 else ""
        recommendations = parts[2].strip() if len(parts) > 2 else ""

        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        reports_dir = os.path.join(base_dir, "reports")
        os.makedirs(reports_dir, exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"report_{timestamp}.pdf"
        filepath = os.path.join(reports_dir, filename)

        doc = SimpleDocTemplate(filepath, pagesize=letter,
                                rightMargin=0.75*inch,
                                leftMargin=0.75*inch,
                                topMargin=0.75*inch,
                                bottomMargin=0.75*inch)

        styles = getSampleStyleSheet()
        
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a1a1a'),
            spaceAfter=30,
            alignment=1
        )

        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#2c3e50'),
            spaceAfter=12,
            spaceBefore=12
        )

        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['BodyText'],
            fontSize=11,
            alignment=4,
            spaceAfter=12
        )

        story = []

        story.append(Paragraph("🛡️ VulnScout Security Report", title_style))
        story.append(Spacer(1, 0.3*inch))

        story.append(Paragraph(title, heading_style))
        story.append(Spacer(1, 0.2*inch))

        timestamp_text = datetime.now().strftime("%B %d, %Y at %H:%M:%S")
        story.append(Paragraph(f"<i>Generated: {timestamp_text}</i>", styles['Normal']))
        story.append(Spacer(1, 0.3*inch))

        story.append(Paragraph("FINDINGS", heading_style))
        story.append(Paragraph(findings if findings else "No findings provided.", body_style))
        story.append(Spacer(1, 0.3*inch))

        if recommendations:
            story.append(Paragraph("RECOMMENDATIONS", heading_style))
            story.append(Paragraph(recommendations, body_style))
            story.append(Spacer(1, 0.3*inch))

        story.append(Spacer(1, 0.5*inch))
        footer_text = "This report was generated by VulnScout AI Security Agent. For support, visit the project repository."
        story.append(Paragraph(f"<i style='font-size: 9'>{footer_text}</i>", styles['Normal']))

        doc.build(story)

        relative_path = os.path.relpath(filepath, base_dir)
        return f"✅ PDF report generated successfully: {relative_path}"

    except Exception as e:
        return f"Failed to generate PDF: {str(e)}"
